# Rutas de las páginas estáticas del sitio
ayuda:
    pattern:  /ayuda
    defaults: { template: 'sitio/ayuda.html.twig' }

privacidad:
    pattern:  /privacidad
    defaults: { template: 'sitio/privacidad.html.twig' }

sobre_nosotros:
    pattern:  /sobre-nosotros
    defaults: { template: 'sitio/sobre-nosotros.html.twig' }
