# Configuración global de los servicios de la aplicación
# Este archivo se importa desde app/config/config.yml
services:
    app.twig.cupon_extension:
        class: AppBundle\Twig\Extension\CuponExtension
        arguments: ["@translator"]
        tags:
            - { name: twig.extension }

    app.request_listener:
        class: AppBundle\Listener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    app.security.owner_voter:
        class: AppBundle\Security\OwnerVoter
        tags:
            - { name: security.voter }

    app.login_listener:
        class: AppBundle\Listener\LoginListener
        scope: container
        arguments: ["@security.authorization_checker", "@router"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
