# Configuración global de los servicios de la aplicación
# Este archivo se importa desde app/config/config.yml
services:

    twig.extension.cupon:
        class: AppBundle\Twig\Extension\CuponExtension
        arguments: [@translator]
        tags:
            - { name: twig.extension }

    cupon.ofertabundle.listener.request:
        class: AppBundle\Listener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    cupon.tiendabundle.security.ownervoter:
        class: AppBundle\Security\OwnerVoter
        tags:
            - { name: security.voter }

    login_listener:
        class: AppBundle\Listener\LoginListener
        scope: container
        arguments: [@security.context, @router]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
